import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css'; 
import "./globals.css"; 
import { NextAuthProvider } from "./dashboard/components/providers";

const inter = Inter({ subsets: ["latin"] });

const theme = {
  fontFamily: 'Poppins, sans-serif', // or your desired font
  primaryColor: 'cyan',
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <MantineProvider theme={theme}>
            {children}
          </MantineProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}