/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fReOFSh4Kpl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function outreach() {
  return (
    <div className="w-full max-w-6xl mx-auto px-4 md:px-6 py-12 md:py-16">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card className="bg-background border-input shadow-sm">
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium">u/redditor123</div>
            </div>
            <Badge variant="outline" className="bg-green-500 text-green-50 font-medium px-2 py-1 rounded-md">
              High
            </Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Reach out to this user about your new product feature that solves a common problem they've discussed on
              Reddit.
            </p>
          </CardContent>
          <CardFooter>
            <Button variant="link" size="sm">
              View Strategy
            </Button>
          </CardFooter>
        </Card>
        <Card className="bg-background border-input shadow-sm">
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium">u/redditor456</div>
            </div>
            <Badge variant="outline" className="bg-yellow-500 text-yellow-50 font-medium px-2 py-1 rounded-md">
              Medium
            </Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Suggest a collaboration opportunity based on this user's recent comments about their interest in your
              industry.
            </p>
          </CardContent>
          <CardFooter>
            <Button variant="link" size="sm">
              View Strategy
            </Button>
          </CardFooter>
        </Card>
        <Card className="bg-background border-input shadow-sm">
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium">u/redditor789</div>
            </div>
            <Badge variant="outline" className="bg-red-500 text-red-50 font-medium px-2 py-1 rounded-md">
              Low
            </Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Offer a free trial of your product to this user based on their recent comments about a related pain point.
            </p>
          </CardContent>
          <CardFooter>
            <Button variant="link" size="sm">
              View Strategy
            </Button>
          </CardFooter>
        </Card>
        <Card className="bg-background border-input shadow-sm">
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium">u/redditor987</div>
            </div>
            <Badge variant="outline" className="bg-green-500 text-green-50 font-medium px-2 py-1 rounded-md">
              High
            </Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Invite this user to participate in your upcoming webinar on a topic they've expressed interest in on
              Reddit.
            </p>
          </CardContent>
          <CardFooter>
            <Button variant="link" size="sm">
              View Strategy
            </Button>
          </CardFooter>
        </Card>
        <Card className="bg-background border-input shadow-sm">
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium">u/redditor654</div>
            </div>
            <Badge variant="outline" className="bg-yellow-500 text-yellow-50 font-medium px-2 py-1 rounded-md">
              Medium
            </Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Offer a discount on your product to this user based on their recent comments about budget constraints.
            </p>
          </CardContent>
          <CardFooter>
            <Button variant="link" size="sm">
              View Strategy
            </Button>
          </CardFooter>
        </Card>
        <Card className="bg-background border-input shadow-sm">
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium">u/redditor321</div>
            </div>
            <Badge variant="outline" className="bg-red-500 text-red-50 font-medium px-2 py-1 rounded-md">
              Low
            </Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Suggest a free trial of your product to this user based on their recent comments about a related pain
              point.
            </p>
          </CardContent>
          <CardFooter>
            <Button variant="link" size="sm">
              View Strategy
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}
